spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  devtools:
    livereload:
      enabled: true
    thymeleaf:
      cache: false
    restart:
      enabled: true
  profiles:
    include: secret

riot:
  url: https://kr.api.riotgames.com/lol

logging:
  level:
    com.jungho.feign: debug

